version: '3'

services:
    web:
        #build:
        #  context: ./web
        #  dockerfile: Dockerfile-nginx
        image: nginx:mainline-alpine
        ports:
            - "8080:80"
        volumes:
            - ./source:/source
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - outside
            - backend
    php:
        build:
          context: ./php
          dockerfile: Dockerfile-php
        #image: php:fpm-alpine3.7
        volumes:
            - ./source:/source
        networks:
            - backend

networks:
    outside:
      internal: false
    backend:
      internal: false
